name: Write Wakatime svg

on:
  push:
  schedule:
    - cron: '0 20 * * *'
    - cron: '0 2 * * *'
    - cron: '0 8 * * *'
    - cron: '0 14 * * *'

jobs:
  release:
    name: Wakatime
    runs-on: [ubuntu-latest]
    permissions:
      contents: write

    steps:
    - name: WakaTime
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.wakatime.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: header, wakatime, activity, community, repositories, metadata
        plugin_wakatime: yes
        plugin_wakatime_days: 3
        plugin_wakatime_limit: 6
        plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
        plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
        plugin_wakatime_url: https://wakapi.dev
        plugin_wakatime_user: XYCode

        plugin_steam: yes
        plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
        plugin_steam_games_limit: 3
        plugin_steam_recent_games_limit: 3
        plugin_steam_user: "76561199089389989"

        plugin_isocalendar: yes
        plugin_isocalendar_duration: half-year
